### ISSUE TITLE
Genomic build (Grch38) imputation reference  panel download

### ISSUE THREAD

**Issue by lizhebio** [immunogenomics/HLA-TAPAS#11]
Where can i download Genomic build (Grch38) imputation reference  panel?

**Comment by yluo86** [comment]
the full panel panel (https://www.nature.com/articles/s41588-021-00935-7) is build in b19/grch37 and can not be downloaded directly due to data restrictions. You can, however, use the Michigan imputation server (https://imputationserver.sph.umich.edu/index.html#!) to impute HLA

**Comment by obedaram** [comment]
Is there any way to have this available through some other means, for instance, I cannot use it to impute from like the all of us cohort, which doesn't allow for data to leave to the Michigan Imputation server
