### ISSUE TITLE
Error running HLAassoc

### ISSUE THREAD

**Issue by isabelleboothman** [immunogenomics/HLA-TAPAS#13]
Hi, I ran the imputation using the Michigan server and am now trying to run HLAasssoc. 
I keep getting this error: 
Traceback (most recent call last):
  File "/home/iboothman/miniconda3/envs/myenv/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/iboothman/miniconda3/envs/myenv/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/iboothman/HLA-TAPAS/HLAassoc/HLAassoc.py", line 10, in <module>
    from HLAassoc.src.reverse_map import reverse_map
  File "/home/iboothman/HLA-TAPAS/HLAassoc/HLAassoc.py", line 10, in <module>
    from HLAassoc.src.reverse_map import reverse_map
ModuleNotFoundError: No module named 'HLAassoc.src'; 'HLAassoc' is not a package

This is the code I ran:  
python -m HLAassoc LINEAR \
    --vcf /home/StorageArray02/Gianpiero/iboothman/HLA_imputation/Michigan/chr6.dose.vcf.gz  \
    --out  /home/StorageArray02/Gianpiero/iboothman/HLA_imputation/Michigan/Random_Irish_samples_HLA. \
    --pheno /home/StorageArray02/Gianpiero/iboothman/HLA_imputation/Random_Irish_samples_HATK.pheno \
    --pheno-name Phenotype 

Not sure why I am getting that error, thanks!

**Comment by catheriz** [comment]
Hi,
Does the HLAssoc use dosage from the imputed file or GT for the analysis?

**Comment by yluo86** [comment]
it uses GT. LINEAR and LOGISTIC use regression coded in PLINK, and OMNIBUS test uses haplotypes based on GT.
