### ISSUE TITLE
No details about the process of making HLA dictionary files 

### ISSUE THREAD

**Issue by LDS-axel** [immunogenomics/HLA-TAPAS#16]
When I tried to make a hla reference panel, I followed your pipeline, but something really confusing me is the format of HLA dictionary and the process to make hla dictionary, which didn't raised in the pipeline.

**Comment by yluo86** [comment]
The MakeReference module is a remake of the original [SNP2HLA](https://software.broadinstitute.org/mpg/snp2hla/makereference_manual.html) package. The python code for doing this can be found here https://github.com/immunogenomics/HLA-TAPAS/blob/master/MakeReference/src/encodeHLA.py.
